import '../styles/modern-normalize.css'
import '../styles/styles.css'
import '../styles/components/header.css'
import '../styles/components/hero.css'
import '../styles/components/about.css'
import '../styles/components/featured.css'
import '../styles/utils.css'